export interface Axis {
  value: string;
  viewValue: string;
  disabled: boolean;
}

const titleDictionary: any = {
  minutes_t: 'Minutes Played',
  tsb: 'Ownership % (latest)',
  price: 'Price (latest)',
  points_t: 'Points',
  points_90: 'Points per 90',
  npxGxA_t: 'npxGI (Understat)',
  npxGxA_90: 'npxGI per 90 (Understat)',
  xGI_t: 'xGI (Understat)',
  xGI_90: 'xGI per 90 (Understat)',
  xGI_FPL_t: 'xGI (Opta)',
  xGI_FPL_90: 'xGI per 90 (Opta)',
  goals_t: 'Goals',
  goals_90: 'Goals per 90',
  npg_t: 'np-Goals',
  npg_90: 'np-Goals per 90',
  npxG_t: 'npxG (Understat)',
  npxG_90: 'npxG per 90 (Understat)',
  xG_t: 'xG (Understat)',
  xG_90: 'xG per 90 (Understat)',
  xG_FPL_t: 'xG (Opta)',
  xG_FPL_90: 'xG (Opta) per 90',
  assists_t: 'Assists',
  assists_90: 'Assists per 90',
  xA_t: 'xA (Understat)',
  xA_90: 'xA per 90 (Understat)',
  xA_FPL_t: 'xA (Opta)',
  xA_FPL_90: 'xA (Opta) per 90',
  goals_assists_t: '(Goals + Assists)',
  goals_assists_90: '(Goals + Assists) per 90',
  shots_t: 'Shots',
  shots_90: 'Shots per 90',
  xPoints_nobonus_t: 'xPoints (no bonus)',
  xPoints_nobonus_90: 'xPoints (no bonus) per 90',
  points_nobonus_t: 'Points (no bonus)',
  points_nobonus_90: 'Points (no bonus) per 90',
  bonus_t: 'Bonus',
  bonus_90: 'Bonus Points Per 90',
  bps_t: 'BPS',
  bps_90: 'BPS Per 90',
  yellow_cards_t: 'Yellow Cards',
  yellow_cards_90: 'Yellow Cards per 90',
  red_cards_t: 'Red Cards',
  red_cards_90: 'Red Cards per 90',
  key_passes_t: 'Key Passes',
  key_passes_90: 'Key Passes per 90',
  defensive_contribution_t: 'Defensive Contribution',
  defensive_contribution_90: 'Defensive Contribution per 90',
  npg_difference_t: '(npg - npxG) (Understat)',
  xGBuildup_t: 'xG Build up',
  xGBuildup_90: 'xG Build up per 90',
  xGChain_t: 'xG Chain',
  xGChain_90: 'xG Chain per 90',
  GC_t: 'Goals Conceded',
  GC_90: 'Goals Conceded per 90',
  xGC_t: 'xG Conceded (Opta)',
  xGC_90: 'xG Conceded per 90 (Opta)',
  OG_t: 'Own Goals',
  OG_90: 'Own Goals per 90',
  CS_t: 'Clean Sheets',
  CS_90: 'Clean Sheets per 90',
  saves_t: 'Saves',
  saves_90: 'Saves per 90',
  pen_saves_t: 'Pen Saves',
  pen_misses_t: 'Pen Misses',
  npxAttRet_t: 'np exp ret (Understat)',
  npxAttRet_90: 'np exp ret /90 (Understat)',
  npAttRet_t: 'np ret',
  npAttRet_90: 'np ret /90',
};

export const roundToNearestDictionary: any = {
  bonus_t: 10,
  bonus_90: 0.5,
  bps_t: 10,
  bps_90: 0.5,
  price: 0.5,
  minutes_t: 100,
  npxG_t: 0.1,
  npxG_90: 0.05,
  xA_t: 0.1,
  xA_90: 0.05,
  npxGxA_t: 0.1,
  npxGxA_90: 0.05,
  xGI_t: 0.1,
  xGI_90: 0.05,
  xGI_FPL_t: 0.1,
  xGI_FPL_90: 0.05,
  points_t: 5,
  points_90: 1,
  goals_t: 1,
  goals_90: 0.05,
  assists_t: 1,
  assists_90: 0.05,
  goals_assists_t: 1,
  goals_assists_90: 0.05,
  tsb: 5,
  shots_t: 5,
  shots_90: 1,
  yellow_cards_t: 1,
  yellow_cards_90: 0.05,
  red_cards_t: 1,
  red_cards_90: 0.05,
  npg_difference_t: 0.5,
  npg_t: 1,
  npg_90: 0.05,
  xG_t: 0.1,
  xG_90: 0.05,
  xG_FPL_t: 0.1,
  xG_FPL_90: 0.05,
  xA_FPL_t: 0.1,
  xA_FPL_90: 0.05,
  key_passes_t: 5,
  key_passes_90: 1,
  xGBuildup_t: 0.1,
  xGBuildup_90: 0.05,
  xGChain_t: 0.1,
  xGChain_90: 0.05,
  points_nobonus_t: 1,
  points_nobonus_90: 0.05,
  xPoints_nobonus_t: 1,
  xPoints_nobonus_90: 0.05,
  npxAttRet_t: 1,
  npxAttRet_90: 0.05,
  npAttRet_t: 0.1,
  npAttRet_90: 0.05,
  GC_t: 1,
  GC_90: 0.05,
  xGC_t: 0.1,
  xGC_90: 0.05,
  saves_t: 1,
  saves_90: 0.05,
  pen_saves_t: 1,
  pen_misses_t: 1,
  OG_t: 1,
  OG_90: 0.05,
  CS_t: 1,
  CS_90: 0.05,
  defensive_contribution_t: 1,
  defensive_contribution_90: 0.05,
};

export function getAxisTitle(axis: string): string {
  return titleDictionary[axis];
}

export function getAxisKeys(): string[] {
  return Object.keys(titleDictionary);
}

export function getAxisViewValueArray(): Axis[] {
  let viewValueArr = [];
  for (let key of getAxisKeys()) {
    viewValueArr.push({
      value: key,
      viewValue: titleDictionary[key],
      disabled: false,
    });
  }
  return viewValueArr;
}
